"""Assembly of the per-category payload and the final JSON artifact."""

import logging
from pathlib import Path
from typing import List, Optional

import numpy as np

from safe_spoon.pipeline.config import PipelineConfig
from safe_spoon.topic_modeling.tm_model import top_docs_per_topic
from safe_spoon.utils.common import save_json

log = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).resolve().parents[3]


def build_category_data(
    cfg: PipelineConfig,
    lda,
    queries_ordered: List[str],
    query_ids_ordered: List[int],
    topic_keys,
    topic_labels: List[str],
    X_cat: np.ndarray,
    n: int,
    selected_model_info: dict,
    embedding_model_used: Optional[str],
) -> dict:
    """Feeds the Themes view with LDA output for a given category, including queries, topic keys/labels, thetas, alphas, tpc_coords, top_docs, and model_info.

    Parameters
    ----------
    cfg : PipelineConfig
        The pipeline configuration object containing various settings.
    lda : LDA model object
        The trained LDA model for the current category.
    queries_ordered : List[str]
        The list of queries ordered according to the LDA model's corpus.
    query_ids_ordered : List[int]
        The list of query IDs ordered according to the LDA model's corpus.
    topic_keys : List[str]
        The list of topic keys generated by the LDA model.
    topic_labels : List[str]
        The list of topic labels generated by the LDA model.
    X_cat : np.ndarray
        The topic distribution matrix for the queries in the current category.
    n : int
        The number of queries in the current category.
    selected_model_info : dict
        Additional metadata about the selected LDA model (e.g., hyperparameters).
    embedding_model_used : Optional[str]
        The name of the embedding model used, if any.

    Returns
    -------
    dict
        A dictionary containing the per-category data payload to be included in the final JSON artifact.
    """
    tm = lda.tm
    tm._compute_s3()
    s3_mat = tm._s3.toarray() if tm._s3 is not None else None
    top_docs = top_docs_per_topic(
        X_cat, queries_ordered, topn=cfg.top_docs_per_topic, s3=s3_mat)

    alphas = tm.get_alphas().tolist()
    tm.load_tpc_coords()
    tpc_coords = [list(xy) for xy in (tm._coords or [])]

    model_path = lda.model_path
    model_path_str = (
        model_path.relative_to(
            _REPO_ROOT) if model_path.is_absolute() else model_path
    ).as_posix()

    return {
        "queries": queries_ordered,
        "query_ids": query_ids_ordered,
        "topic_keys": topic_keys,
        "topic_labels": topic_labels,
        "thetas": [[round(float(v), 4) for v in row] for row in X_cat],
        "alphas": [round(float(a), 6) for a in alphas],
        "tpc_coords": [[round(c, 4) for c in xy] for xy in tpc_coords],
        "top_docs": top_docs,
        "n": n,
        "model_info": {
            "model_path": model_path_str,
            "n_topics": lda.num_topics,
            "embedding_model": embedding_model_used,
            **selected_model_info,
        },
    }


def build_category_tree_payload(
    flat_nodes: list,
    root_id: str,
    valid_local: List[int],
    cuts: list,
    min_d: float,
    max_d: float,
    n: int,
    n_oov: int,
) -> dict:
    """Package Groups (hierarchical-clustering output) view for a given category's hierarchical-clustering output, i.e., dendrogram
    nodes, root_id, valid indices, cut levels, min/max linkage distances.

    Parameters
    ----------
    flat_nodes : list
        The flattened list of dendrogram nodes for the category.
    root_id : str
        The identifier of the root node in the dendrogram.
    valid_local : List[int]
        The list of valid indices for the queries in the category.
    cuts : list
        The list of cut levels for the dendrogram.
    min_d : float
        The minimum linkage distance in the dendrogram.
    max_d : float
        The maximum linkage distance in the dendrogram.
    n : int
        The number of queries in the category.
    n_oov : int
        The number of out-of-vocabulary queries in the category.

    Returns
    -------
    dict
        A dictionary containing the per-category tree payload to be included in the final JSON artifact.

    """
    return {
        "nodes": flat_nodes,
        "root_id": root_id,
        "indices": valid_local,
        "cuts": cuts,
        "min_dist": round(min_d, 4),
        "max_dist": round(max_d, 4),
        "n": n,
        "n_oov": n_oov,
    }


def save_payload(
    cfg: PipelineConfig,
    categories: List[str],
    data_by_category: dict,
    trees_by_category: dict,
) -> None:
    """
    Save the final JSON artifact containing the per-category data and tree payloads.
    """

    payload = {
        "categories": categories,
        "data_by_category": data_by_category,
        "trees_by_category": trees_by_category,
        "n_repr": cfg.n_repr_queries,
    }
    log.info("Saving JSON to %s", cfg.output_json)
    save_json(payload, cfg.output_json)
    log.info("Done * %s", cfg.output_json)
